services:
  - docker
sudo: true
before_script:
  - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
script:
  - make build
  - make test
  - make push
env:
  global:
  - secure: uolRFVwWxKqWL3iBnSnol3vlPNZu/F2+Vmb93MVrLT1mjPVEAxifkh7NghjuipNKuQLlrqhHCqSxDo0c1ZMGaXk6Y66q2enlsnoIc4trUDf3X0yqHINE9u2LTaYC8DlnuwZi/jp2qhoXEF1cfHJ8SmXA3RhUSP2hiGAHLlEmTzhykTd3HRadej1flTyrPS7Lm/alHfta5dc62DKq+zVBEKuz+MvGQ/Y5CpnGD0qEErASC2wSt4AWsDELcWgcC28sPinz09FNVxA+Zk4HXL0f6zUcf50OQp4qu8hX4P0mu1arfkaUmYvtwOhq0xrl1tO0T7QqLRND2unZj3E4bioeNsjJbOel4GQ7ObJ+9qupxLfT1NBb2Sh6wZRm9O8EZc5Zlps0FFh2SR8ue9jFMu9NT2OZANDWNf53McSPKzLSPZPJaIW6r1NRaW6FdN7zDAAvWk+qCe0NG9xi2b3hW3vjFLROMKLKkhBfOTeuTtXjoCYrWC2TeAYG61PbynliM8nI4j5QpkX+3YUail1ZO1oG6g7X1bLL9IjLXDJ1DN5WGAY1HTbO/G3UmQnbyPjuu9NSKKoH3GJ2I5gTUNPEwcUTpbAZk4OdzFkIK/Pxrs1F0Ba5dBK0W33Ozmcumupw2qVbVGB7ugHK561VShcJPMgLwyjdJXMRPk5duj8YtFGQvj8=
  - secure: bBipQr5vyL7jzNPNJaESIWWdp0dYVR8KT38cWwhXn6se9xC+EysxVj8HN7AVOGMKlcjyZy7QNx9K6BMdreq+nNZ3rrN8EJQD0rlzOR1GWUvbNiGnX0tHm1C2oGYTvZt4nSIecfw9pWeq5vYH6blStfpNOKZEvA2hhJD3LStNqL6sTwrxLj+ojR45L6b5IvhpTELFHyXe3Jx1RtANBXL3IMVaemtPm6UHyIrIteUSjy1qW1jU9HH7DBafkcOgJEn3WgawFbSIHwWyt3PH9NG+71UchqYRCuun3nQKR2e+lLna866lwYF1lHcswwpTHErE+nkmhzHk/Vaau6fwna32RUo6aYxIICUzuZDVEirM0Jq1UW6Tf/uX4zvJsVZyfNCgHWjQbLmEGfav7W9zgt/jnBWG7mtknqw8ub1Shs9faRGCN7+9F8WbbAWUWBhEM4Nm1UBMISFcqdpQ1k4v2YN7blt/1hg6uzxBqcojr3VNnpAkqYaPqQpRv4CQ6f4A5akhZ+QKrA32kuspFpF1Y93VGWYX0QHMO2m14IeoBu+NodTnGHLDxq62mpg2fysOnx2nlrcYRNQmJbpVfp0BnLqgd69rVlUjcHms3pMWR1npprEMuqmybrPpca66AP/WhnLxAQSRWKBtIrbcmfABaIBUWpHsTPkmF6++nFMDhthEIHE=
