version: 2.1
jobs:
  build:
    branches:
      ignore:
        - /dg\/.*/
    machine: true
    steps:
      - run: 
          name: Docker Login
          command: echo ${DOCKER_PASS} | docker login -u ${DOCKER_USER} --password-stdin
      - checkout
      - run: 
          name: Build
          command: make build
      - run: 
          name: Test
          command: make test
      - run: 
          name: Push
          command: make push
workflows:
  version: 2
  docker-build:
    jobs:
      - build:
          context: docker build
