version: 2.1
jobs:
  build:
    machine: true
    steps:
      - run: 
          context: docker build
          command: echo ${DOCKER_PASS} | docker login -u ${DOCKER_USER} --password-stdin
      - run: make build
      - run: make test
      - run: make push